#SPDX-License-Identifier: MIT-0
---
# tasks file for my_custom_role

- name: print message
  debug:
    msg: "this is role task"

- name: print msg through variable
  debug:
    msg: "{{text}}"

- name: Install Apache2
  apt:
    name: "{{pkg}}"
    state: latest
    update_cache: yes
  become: true

- name: Copy index.html file
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: add second block in index.html
  blockinfile:
    path: /var/www/html/index.html
    marker: "# {mark} ANSIBLE SECOND BLOCK"
    block: |
      <div>
        <h1>Good Morning</h1>
          <p>This is inserted by Ansible.</p>
        </div>