- name: Installation File
  hosts: all
  become: true
  task:
    - name: Install Apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"