- name: Installation File
  hosts: all
  become: true
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install httpd
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"