- name: example of line in file
  hosts: all
  become: true
  tasks:
    - name: add line to existing index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "<h3> Hello Ansible </h3>"
        insertafter: "<h1>"
