- name: example of line in file
  hosts: all
  become: true
  tasks:
    - name: add line to existing index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "<h3> Hello from Ansible </h3>" 
        insertafter: "<h1>" 

    # # remove line
    # - name: Remove HTML line
    #   lineinfile:
    #     path: /var/www/html/index.html
    #     # line: "<h3> Hello from Ansible </h3>"
    #     regexp: '.*Hello from Ansible.*'
    #     state: absent
        
    - name: add block to existing index.html
      blockinfile:
        path: /var/www/html/index.html
        block: |
          <div>
            <h1>Hello Gaurav</h1>
            <p>This is inserted by Ansible.</p>
          </div>
        
    # # remove block
    # - name: Remove HTML block
    #   blockinfile:
    #     path: /var/www/html/index.html
    #     state: absent
