- name: install multiple values
  hosts: all
  become: true
  tasks:
    - name: loop check
      package:
        name: "{{item}}"
        state: latest
      loop:
        - vim
        - wget
        - nginx

    - name: deployment
      copy: 
        src: index.html
        dest: /var/www/html/index.html