- name: install multiple values
  hosts: all
  tasks:
    - name: loop check
      package:
        name: "{{item}}"
        state: latest
      loop: 
        - vim
        - wget
        - nginx
        - httpd