- name: install multiple values
  hosts: all
  become: true
  tasks:
    - name: loop check
      package:
        name: "{{item}}"
        state: latest
      loop:
        - vim
        - wget
        - nginx